version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: sla_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - sla_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-api:
    build: ./nestjs-api
    container_name: sla_nestjs
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${API_PORT}:3000"
      - "9229:9229" # Debug port
    volumes:
      - ./nestjs-api:/app
      - nestjs_api_node_modules:/app/node_modules
    command: sh -c "npm run migration:run && npm run start:debug"
  # nextjs-web:
  #   build: ./nextjs-web
  #   container_name: sla_nextjs
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - nestjs-api
  #   ports:
  #     - "${WEB_PORT}:3001"
  #     - "9231:9231"
  #   volumes:
  #     - ./nextjs-web:/app
  #     - /app/node_modules
  #   command: sh -c "npm run debug"

  nextjs-web:
    build: ./nextjs-web
    container_name: sla_nextjs
    env_file:
      - ./.env
    depends_on:
      - nestjs-api
    # environment:
    #   - NODE_OPTIONS=--inspect=0.0.0.0:9231
    ports:
      - "${WEB_PORT}:3001"
      - "9231:9231" # Debug port (host:container) - NextJS uses 9231 in container
    volumes:
      - ./nextjs-web:/app
      - nextjs_web_node_modules:/app/node_modules
    # command: sh -c "npm run debug"
    command: sh -c "npm run dev"
    # command: ["npx", "next", "dev", "-p", "3001"]

volumes:
  sla_pg_data:
  nestjs_api_node_modules:
  nextjs_web_node_modules:
