version: "3.9"
services:
  postgres:
    image: postgres:15
    pull_policy: if_not_present
    container_name: sla_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'UTC'  # System timezone
      PGTZ: 'UTC'  # PostgreSQL timezone
    ports:
      - "5434:5432"
    volumes:
      - sla_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sla-network

  nestjs-api:
    build: ./nestjs-api
    container_name: sla_nestjs
    env_file:
      - ./.env
    environment:
      # TYPEORM_HOST: 10.32.35.27
      # TYPEORM_PORT: 5433
      # TYPEORM_HOST: postgres
      # TYPEORM_PORT: 5432
      # TYPEORM_USERNAME: postgres
      # TYPEORM_PASSWORD: postgres
      # TYPEORM_DATABASE: sla
      API_PORT: 3000
      WEB_PORT: 3001
      NEST_JWT_SECRET: your_jwt_secret_here
      HMAC_SHARED_SECRET: your_hmac_secret_here
      DOCKER_RUNTIME: prod
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${API_PORT}:3000"
      - "9229:9229" # Debug port
    volumes:
      - ./nestjs-api:/app
      # - nestjs_api_node_modules:/app/node_modules
    command: sh -c "npm install --production=false && npm run migration:run && npm run start:debug"
    # command: sh -c "npm run migration:run && npm run start:debug"
    networks:
      - sla-network

  nextjs-web:
    build: ./nextjs-web
    container_name: sla_nextjs
    env_file:
      - ./.env
    depends_on:
      - nestjs-api
    environment:
      - API_URL=http://nestjs-api:3000
    ports:
      - "${WEB_PORT}:3001"
      - "9231:9231" # Debug port (host:container) - NextJS uses 9231 in container
    volumes:
      - ./nextjs-web:/app
      - nextjs_web_node_modules:/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - sla-network

networks:
  sla-network:
    driver: bridge

volumes:
  sla_pg_data:
  nextjs_web_node_modules:
